### ISSUE TITLE
Programs not saving to database

### ISSUE THREAD

**Issue by terracoda** [phetsims/paper-land#202] opened 2023-11-16 02:06 UTC
**Copied Programs not Saving**
I copied my X and X squared programs Tuesday around 4 pm CT, and then when I loaded PP the next morning they were not there. I assumed I had missed a step or had done something wrong. I copied them all again, and just noticed my copies did not stick. The database looks the same as it did this morning.

**To Reproduce**
1. Go to 'ts-creator-tests'
2. Copy the X Tile program
3. Change the auto-generated number
4. Save Program and send to Play ground
5. They copied program should exist and work.
6. Quit Paper Playground
7. Quit everything
8. Re-start and re-open and copy might not be there.

I just happened to have taken a screenshot this afternoon while making copies. You can see I have copies of X Tiles:
<img width="781" alt="Screenshot 2023-11-15 at 11 38 43 AM" src="https://github.com/phetsims/paper-land/assets/1902116/d6ea4a71-8ebb-4fa8-b034-2a6ff844dcf2">

I don't have those or the rest of my copies anymore.

**Comment by jessegreenberg** [comment] 2023-11-16 02:20
I just reproduced the problem with the tactiles project. It is another case of the payload being too large, we are getting this response back from the server: "413 (Payload Too Large)"

So it seems we cannot save the entire project all at once. This one is going to be tricker than #188 because the projects table only has one entry for the project data - a JSON object for the entire thing. We will probably have to change the table or edit the saved JSON without reloading the whole thing.

**Comment by jessegreenberg** [comment] 2023-11-16 13:44
The above commit is working well, its in a feature branch `chunk-saves`. Before merging into main I want to 
- [ ] Make sure this strategy works/handles sending multiple save requests before the first request finishes.
- [ ] Add a timeout so that if the server doesn't receive all chunks, we bail corectly.
- [ ] Look for other places where this payload error can happen.
- [ ] Lots of testing of save/load for existing projects.

**Comment by jessegreenberg** [comment] 2023-11-16 15:52
> Look for other places where this payload error can happen.

Inspecting the api, here is where this can happen again potentially:

- /api/spaces/:spaceName/programs (POST):  - When you create a new program from the camera page. Will happen if code is too large.
- /api/spaces/:spaceName/programs/add-premade-program (POST): Sends a single program to playground from Creator, part of the chunking from #188. If the program is too large, we will hit this.
- /api/creator/templates (PUT): Saves a new template for creator. Just like this issue, if the template is has ~200 components or more, we will hit this.
- /api/creator/templates/update/save (PUT): Again, if template is massive when you update it, this will happen.
- /api/creator/maintenance/updateSchema (POST): (Not really worried about this, its for development use)

**Comment by jessegreenberg** [comment] 2023-11-16 16:37
This was merged into main. I did some spot checking on main and it is OK.

**Comment by jessegreenberg** [comment] 2023-11-16 16:48
@brettfiedler can you please review https://github.com/phetsims/paper-land/issues/202#issuecomment-1814735146 and let me know if there is anything else you would like to do here? For example, place a limit on the number of components a single program can have or something like that?

**Comment by brettfiedler** [comment] 2024-05-10 18:06
Opened a new issue in #250 to track future occurences.

**Closed by brettfiedler** 2024-05-10 18:06 UTC
Labels: type:bug, status:ready-for-review
